package utdallas;

import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

public class MethodTransformVisitor {

    private String className;
    private int line;


     /*    * @param mv
     * @param className
     */
    public MethodTransformVisitor(final MethodVisitor mv, String className) {
        super(ASM5, mv);
        this.className = className;
    }

    @Override
    public void visitLineNumber(int line, Label start) {
        if (0 != line) {
            this.line = line;
            /**
             * Generated by ASMfier
            */

            mv.visitLdcInsn(className);
            mv.visitLdcInsn(new Integer(line));
            mv.visitMethodInsn(INVOKESTATIC, "java/lang/Integer", "valueOf", "(I)Ljava/lang/Integer;", false);
            mv.visitMethodInsn(INVOKESTATIC, "edu/utd/CoverageCollection", "visitLine", "(Ljava/lang/String;Ljava/lang/Integer;)V", false);
            super.visitLineNumber(line, start);
        }
    }



}
